#!/bin/bash
 
# Load resources
 
xrdb -merge .Xresources
 
# Set up an icon tray
#trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --widthtype request --alpha 0 --tint 0x2d2d2d --height 16 &
#trayer --edge top --align right --SetDockType true --SetPartialStrut true \
# --expand true --width 10 --transparent true --tint 0x2d2d2d --height 12 &

# Set the background color<
 
#xsetroot -solid midnightblue
 
# Fire up apps
 
feh --bg-scale ~/Pictures/bg/1496390939106.png:large.jpeg

#xscreensaver -no-splash &

#nm-applet &
#if [ -x /usr/bin/nm-applet ] ; then
#   nm-applet --sm-disable &
#fi
 
#if [ -x /usr/bin/gnome-power-manager ] ; then
#   sleep 3
#   gnome-power-manager &
#fi
#trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true --alpha 0 --tint 0x2d2d2d --height 16 && nm-applet
 
exec xmonad

#trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true --alpha 0 --tint 0x2d2d2d --height 16 &

#nm-applet &

